name: Publish Package

on:
  push:
    branches:
      - main
env:
  NODE_VERSION: ''
  PNPM_VERSION: ''

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Read Node.js version ${{env.NODE_VERSION}}
        uses: ./.github/actions/read-node-version.yml

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      # - name: Publish to npm registry
      #   run: pnpm publish --access public
