name: Publish Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node version ${{steps.nvm.outputs.NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{steps.nvm.outputs.NODE_VERSION}}
          registry-url: https://npm.pkg.github.com/
          scope: '@sravanth-c2fo'
      - name: Read .pnpmv
        run: echo ::set-output name=PNPM_VERSION::$(cat .pnpmv)
        id: pnpm
      - name: Use pnpm version ${{steps.pnpm.outputs.PNPM_VERSION}}
        uses: pnpm/action-setup@v2
        with:
          version: ${{steps.pnpm.outputs.PNPM_VERSION}}

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
